apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: prod
spec:
  type: ClusterIP
  ports:
    - targetPort: 8082
      port: 8082
  selector:
    app: notification-service
