spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://127.0.0.1:8888
  # rabbitmq settings
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  # mongodb settings
  data:
    mongodb:
      username: root
      password: 11111111
      uri: mongodb://root:11111111@localhost:27017/notification-service?authSource=admin

embedded:
  mongodb:
    version: 5.0.6

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
