server:
  port: 8082
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: notification-service
  jackson:
    time-zone: Asia/Seoul
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, prometheus