# application-local.yml
spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://127.0.0.1:8888
  # rabbitmq settings
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  # mongodb settings
  data:
    mongodb:
      username: root
      password: 11111111
      uri: mongodb://root:11111111@localhost:27017/notification-service?authSource=admin
      auto-index-creation: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 11111111

#  mongodb:
#    embedded:
#      version: 5.0.6

#cloud:
#  aws:
#    credentials:
#      access-key: "" # 실험용 개인계정 키
#      secret-key: "" # 실험용 개인계정 키
#    region:
#      static: ap-northeast-2
#    sqs:
#      region: ap-northeast-1
#    stack:
#      auto: false


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        cloud:
          aws: DEBUG
